name: CI for gRPC Microservices

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26'

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run Tests
      run: |
        for dir in go-grpc-*; do
          cd $dir
          go test ./...
          cd ..
        done

    - name: Run Security Vulnerability Check
      run: |
        for dir in go-grpc-*; do
          cd $dir
          govulncheck ./...
          cd ..
        done
